# Generated by Django 4.1.5 on 2023-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=256)),
                ('manufacturer', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('belonging', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=256)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
            ],
        ),
    ]
