# Generated by Django 4.1.5 on 2023-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='owner',
            field=models.CharField(default='', max_length=256),
        ),
    ]
