# Generated by Django 4.1.5 on 2023-02-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_itemmodel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='index.itemmodel')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='index.itemmodel')),
            ],
        ),
    ]
