# Generated by Django 4.1.5 on 2023-02-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_itemrelationmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='itemrelationmodel',
            options={'verbose_name': 'Связь элементов', 'verbose_name_plural': 'Связи элементов'},
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
